# Generated by Django 3.2.6 on 2021-08-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_vacancy', models.CharField(max_length=50, verbose_name='Запрос вакансии')),
                ('city', models.CharField(max_length=20, verbose_name='Регион')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
            ],
        ),
        migrations.CreateModel(
            name='Output_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=50, verbose_name='Вакансия')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('salary', models.CharField(blank=True, max_length=20, verbose_name='Зарплата')),
                ('skills', models.CharField(blank=True, max_length=255, verbose_name='Навыки')),
                ('company', models.CharField(max_length=50, verbose_name='Компания')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Адрес')),
                ('url_link', models.URLField(verbose_name='Ссылка на вакансию')),
                ('input_vac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.search', verbose_name='ForeignKey')),
            ],
        ),
    ]
